# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\myates2\PycharmProjects\foram-v2-nogit\foram-v2-gui1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLabel
from PyQt5.QtGui import QImage

from gui_functions import *
import cv2, imutils, time, serial

import numpy as np
import cv2
from Amscope_Camera.camera import *


class WorkerThread(QtCore.QObject):
    update = QtCore.pyqtSignal()

    def __init__(self):
        self.count = 0
        super().__init__()

    @QtCore.pyqtSlot()
    def run(self):
        while True:
            # Long running task ...
            self.update.emit()
            time.sleep(0.2)

class Ui_Foram_GUI_proto(object):

    def setupUi(self, Foram_GUI_proto):
        # initialize class variables
        self.cam = ToupCamCamera()
        self.cam.open()
        self.arduino = serial.Serial(port='COM4', baudrate=9600, timeout=.1)
        self.arduino.write(str.encode(str(0)))
        time.sleep(2)

        Foram_GUI_proto.setObjectName("Foram_GUI_proto")
        Foram_GUI_proto.resize(800, 750)
        self.centralwidget = QtWidgets.QWidget(Foram_GUI_proto)
        self.centralwidget.setObjectName("centralwidget")


        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 790, 595))

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 650, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.changeSolenoid1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 650, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.changeSolenoid2)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 650, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.changeSolenoid3)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(350, 650, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.changeSolenoid4)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(690, 650, 93, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.saveImg)
        Foram_GUI_proto.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Foram_GUI_proto)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuPrototype = QtWidgets.QMenu(self.menubar)
        self.menuPrototype.setObjectName("menuPrototype")
        Foram_GUI_proto.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Foram_GUI_proto)
        self.statusbar.setObjectName("statusbar")
        Foram_GUI_proto.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuPrototype.menuAction())

        self.retranslateUi(Foram_GUI_proto)
        QtCore.QMetaObject.connectSlotsByName(Foram_GUI_proto)

        # new
        self.count = 0
        super().__init__()
        self.worker = WorkerThread()
        self.workerThread = QtCore.QThread()
        self.workerThread.started.connect(self.worker.run)  # Init worker run() at startup (optional)
        self.worker.update.connect(self.update)
        self.worker.moveToThread(self.workerThread)  # Move the Worker object to the Thread object
        self.workerThread.start()

        self.solenoid = Solenoids()

    def update(self):
        self.img = np.array(self.cam.get_pil_image())
        frame = cv2.resize(self.img, (780, 585))
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        self.image = QImage(frame, frame.shape[1], frame.shape[0], frame.strides[0], QImage.Format_RGB888)
        self.label.setPixmap(QtGui.QPixmap(self.image))

    def retranslateUi(self, Foram_GUI_proto):
        _translate = QtCore.QCoreApplication.translate
        Foram_GUI_proto.setWindowTitle(_translate("Foram_GUI_proto", "MainWindow"))
        self.pushButton.setText(_translate("Foram_GUI_proto", "Solenoid 1"))
        self.pushButton_2.setText(_translate("Foram_GUI_proto", "Solenoid 2"))
        self.pushButton_3.setText(_translate("Foram_GUI_proto", "Solenoid 3"))
        self.pushButton_4.setText(_translate("Foram_GUI_proto", "Solenoid 4"))
        self.pushButton_5.setText(_translate("Foram_GUI_proto", "Save"))
        self.menuPrototype.setTitle(_translate("Foram_GUI_proto", "Prototype"))

    def changeSolenoid1(self):
        self.solenoid.changeSolenoid(1)
        self.arduino.write(str.encode(str(1)))

    def changeSolenoid2(self):
        self.solenoid.changeSolenoid(2)
        self.arduino.write(str.encode(str(2)))

    def changeSolenoid3(self):
        self.solenoid.changeSolenoid(3)
        self.arduino.write(str.encode(str(3)))

    def changeSolenoid4(self):
        self.solenoid.changeSolenoid(4)
        self.arduino.write(str.encode(str(4)))

    def saveImg(self):
        path = 'images/cam_test_1/test_image-{:02d}.jpg'.format(1)
        self.cam.save(path)
        print("image saved")
        time.sleep(0.2)

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Foram_GUI_proto = QtWidgets.QMainWindow()
    ui = Ui_Foram_GUI_proto()
    ui.setupUi(Foram_GUI_proto)
    Foram_GUI_proto.show()
    sys.exit(app.exec_())
